#!/usr/bin/env bash
# check-packaging-sync.sh: fail when packaging metadata drifts from the
# workspace version.
#
# This guard exists because of issue #72: the AUR package sat at 0.6.0
# while the workspace was two releases ahead, so `hwatu setup` (shipped
# in 0.6.1) did not exist for anyone who installed via yay. The failure
# was invisible until a user reported it. Drift is now a CI failure.
#
# Checked invariants:
#   1. packaging/PKGBUILD pkgver == workspace version
#   2. packaging/aur/PKGBUILD is identical to packaging/PKGBUILD
#   3. packaging/aur/.SRCINFO agrees with the PKGBUILD it mirrors
#   4. server.json (MCP registry manifest) version == workspace version
set -euo pipefail

repo_root=$(cd "$(dirname "$0")/.." && pwd)
cd "$repo_root"
status=0

fail() {
  echo "packaging drift: $*" >&2
  status=1
}

# Workspace version is the single source of truth.
workspace_version=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml | head -1)
if [ -z "$workspace_version" ]; then
  echo "error: could not read workspace version from Cargo.toml" >&2
  exit 2
fi
echo "workspace version: $workspace_version"

# 1. PKGBUILD pkgver.
pkgver=$(sed -n 's/^pkgver=\(.*\)$/\1/p' packaging/PKGBUILD | head -1)
if [ "$pkgver" != "$workspace_version" ]; then
  fail "packaging/PKGBUILD pkgver=$pkgver != workspace $workspace_version"
fi

# 2. The staged AUR copy must not diverge from the canonical PKGBUILD.
if ! diff -q packaging/PKGBUILD packaging/aur/PKGBUILD >/dev/null 2>&1; then
  fail "packaging/aur/PKGBUILD differs from packaging/PKGBUILD"
fi

# 3. .SRCINFO is generated from the PKGBUILD, so its fields must agree.
#    (Generated by makepkg --printsrcinfo, which is Linux-only, hence
#    this field-level check rather than a regenerate-and-diff.)
srcinfo_ver=$(sed -n 's/^[[:space:]]*pkgver = \(.*\)$/\1/p' packaging/aur/.SRCINFO | head -1)
if [ "$srcinfo_ver" != "$workspace_version" ]; then
  fail "packaging/aur/.SRCINFO pkgver=$srcinfo_ver != workspace $workspace_version"
fi

pkg_sha=$(sed -n "s/^sha256sums=('\(.*\)')$/\1/p" packaging/PKGBUILD | head -1)
srcinfo_sha=$(sed -n 's/^[[:space:]]*sha256sums = \(.*\)$/\1/p' packaging/aur/.SRCINFO | head -1)
if [ "$pkg_sha" != "$srcinfo_sha" ]; then
  fail ".SRCINFO sha256 ($srcinfo_sha) != PKGBUILD sha256 ($pkg_sha)"
fi

pkg_license=$(sed -n "s/^license=('\(.*\)')$/\1/p" packaging/PKGBUILD | head -1)
srcinfo_license=$(sed -n 's/^[[:space:]]*license = \(.*\)$/\1/p' packaging/aur/.SRCINFO | head -1)
if [ "$pkg_license" != "$srcinfo_license" ]; then
  fail ".SRCINFO license ($srcinfo_license) != PKGBUILD license ($pkg_license)"
fi

# The source tarball must point at the version being packaged.
if ! grep -q "archive/v${workspace_version}.tar.gz" packaging/aur/.SRCINFO; then
  fail "packaging/aur/.SRCINFO source URL does not reference v$workspace_version"
fi

# 4. MCP registry manifest.
if [ -f server.json ]; then
  server_version=$(python3 -c 'import json;print(json.load(open("server.json"))["version"])' 2>/dev/null || echo "")
  if [ -n "$server_version" ] && [ "$server_version" != "$workspace_version" ]; then
    fail "server.json version=$server_version != workspace $workspace_version"
  fi
fi

if [ "$status" -eq 0 ]; then
  echo "packaging metadata is in sync at $workspace_version"
else
  echo "" >&2
  echo "Fix: update packaging/PKGBUILD (pkgver + sha256sums), copy it to" >&2
  echo "packaging/aur/PKGBUILD, update packaging/aur/.SRCINFO to match," >&2
  echo "and bump server.json. See scripts/aur-publish.sh." >&2
fi
exit "$status"
